version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app-server:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - local.env
    depends_on:
      - redis
      - mongo

  app-client:
    build: ./app-client
    environment:
      - HOST=app-server:8080

volumes:
  mongo_data:
